[package]
name = "zippity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert2 = "0.3.11"
crc32fast = "1.3.2"
lru = "0.12.0"
packed_struct = "0.10.1"
pin-project = "1.1.3"
thiserror = "1.0.53"
tokio = { version = "1.32.0", features = ["sync", "fs", "io-util"] }

[dev-dependencies]
proptest = "1.3.1"
test-strategy = "0.3.1"
zip = "0.6.6"
tokio = { version = "1.32.0", features = ["rt"] }
